### PR TITLE
Overhaul RadioTapWriter

### PR DESCRIPTION
**Pull request by DDoSolitary**

### CODE REVIEW

**Comment by DDoSolitary** [comment]
Sure, though it won't be possible to add test case for ba2216e6e923c65798ccce988af485ffc7ac74d2, because it only causes problems on very specific environments like qemu-system-x86.

**Comment by mfontanini** [comment]
Yeah I imagined that wouldn't normally happen. Mostly for the padding one, I'm surprised I didn't caught that with some existing test.

**Comment by DDoSolitary** [comment]
@mfontanini Done.

**Comment by mfontanini** [comment]
Thanks!

**Pull request merged**
